### ISSUE TITLE
kindly help how to resolve this issue 

### ISSUE THREAD

**Issue by pvssrikanth** [betancourtf/pdfsvc#2]
./pdfsvc/requirements.txt
((srik) ) srikanth@srikanth-vm:~/srik/dj/pdfsvc$ vi pdfsvc/requirements.txt 
((srik) ) srikanth@srikanth-vm:~/srik/dj/pdfsvc$ docker-compose up
WARNING: Found orphan containers (pdfsvc_locust_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting pdfsvc_db_1 ... 
Starting pdfsvc_web_1 ... 
Starting pdfsvc_db_1
Starting pdfsvc_web_1 ... done
Attaching to pdfsvc_db_1, pdfsvc_web_1
db_1   | 
db_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1   | 
db_1   | 2022-01-15 16:43:31.592 UTC [1] LOG:  starting PostgreSQL 13.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db_1   | 2022-01-15 16:43:31.593 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2022-01-15 16:43:31.593 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2022-01-15 16:43:31.594 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2022-01-15 16:43:31.596 UTC [22] LOG:  database system was shut down at 2022-01-15 16:42:00 UTC
db_1   | 2022-01-15 16:43:31.599 UTC [1] LOG:  database system is ready to accept connections
web_1  | Watching for file changes with StatReloader
web_1  | Watching for file changes with StatReloader

web_1  | [15/Jan/2022 16:47:04] "GET /admin/ HTTP/1.1" 302 0
web_1  | [15/Jan/2022 16:47:04] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2214
web_1  | [15/Jan/2022 16:47:05] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:05] "GET /static/admin/css/base.css HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:05] "GET /static/admin/css/login.css HTTP/1.1" 200 939
web_1  | [15/Jan/2022 16:47:05] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:05] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:05] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:05] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:05] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:13] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
web_1  | [15/Jan/2022 16:47:14] "GET /admin/ HTTP/1.1" 200 4731
web_1  | [15/Jan/2022 16:47:14] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:15] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:15] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:15] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:19] "GET /admin/page_request/pagerequest/add/ HTTP/1.1" 200 7460
web_1  | [15/Jan/2022 16:47:19] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:19] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:19] "GET /static/admin/js/core.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:19] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
web_1  | [15/Jan/2022 16:47:19] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:20] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:20] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:20] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:20] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:20] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:20] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
web_1  | [15/Jan/2022 16:47:20] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
db_1   | 2022-01-15 16:47:24.700 UTC [41] ERROR:  relation "page_request_pagerequest" does not exist at character 13
db_1   | 2022-01-15 16:47:24.700 UTC [41] STATEMENT:  INSERT INTO "page_request_pagerequest" ("owner_id", "url", "status", "error_msg", "pdf_file") VALUES (1, 'https://iib.gov.in', 'P', NULL, '') RETURNING "page_request_pagerequest"."id"
db_1   | 2022-01-15 16:47:24.719 UTC [41] ERROR:  relation "page_request_pagerequest" does not exist at character 234
db_1   | 2022-01-15 16:47:24.719 UTC [41] STATEMENT:  SELECT "page_request_pagerequest"."id", "page_request_pagerequest"."owner_id", "page_request_pagerequest"."url", "page_request_pagerequest"."status", "page_request_pagerequest"."error_msg", "page_request_pagerequest"."pdf_file" FROM "page_request_pagerequest" LIMIT 21
web_1  | Internal Server Error: /admin/page_request/pagerequest/add/
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1  |     return self.cursor.execute(sql, params)
web_1  | psycopg2.errors.UndefinedTable: relation "page_request_pagerequest" does not exist
web_1  | LINE 1: INSERT INTO "page_request_pagerequest" ("owner_id", "url", "...
web_1  |                     ^
web_1  | 
web_1  | 
web_1  | The above exception was the direct cause of the following exception:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 616, in wrapper
web_1  |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1  |     response = view_func(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1  |     response = view_func(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
web_1  |     return view(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1657, in add_view
web_1  |     return self.changeform_view(request, None, form_url, extra_context)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1  |     return bound_method(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1  |     response = view_func(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
web_1  |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
web_1  |     self.save_model(request, new_object, form, not add)
web_1  |   File "/opt/pdfsvc/page_request/admin.py", line 13, in save_model
web_1  |     obj.save()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
web_1  |     self.save_base(using=using, force_insert=force_insert,
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
web_1  |     updated = self._save_table(
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
web_1  |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
web_1  |     return manager._insert(
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
web_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
web_1  |     return query.get_compiler(using=using).execute_sql(returning_fields)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
web_1  |     cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
web_1  |     return super().execute(sql, params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
web_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
web_1  |     return executor(sql, params, many, context)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1  |     return self.cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
web_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1  |     return self.cursor.execute(sql, params)
web_1  | django.db.utils.ProgrammingError: relation "page_request_pagerequest" does not exist
web_1  | LINE 1: INSERT INTO "page_request_pagerequest" ("owner_id", "url", "...
web_1  |                     ^
web_1  | 
web_1  | Internal Server Error: /admin/page_request/pagerequest/add/
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1  |     return self.cursor.execute(sql, params)
web_1  | psycopg2.errors.UndefinedTable: relation "page_request_pagerequest" does not exist
web_1  | LINE 1: INSERT INTO "page_request_pagerequest" ("owner_id", "url", "...
web_1  |                     ^
web_1  | 
web_1  | 
web_1  | The above exception was the direct cause of the following exception:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1  |     response = get_response(request)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
web_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 616, in wrapper
web_1  |     return self.admin_site.admin_view(view)(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1  |     response = view_func(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
web_1  |     response = view_func(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
web_1  |     return view(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1657, in add_view
web_1  |     return self.changeform_view(request, None, form_url, extra_context)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1  |     return bound_method(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
web_1  |     response = view_func(request, *args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
web_1  |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
web_1  |     self.save_model(request, new_object, form, not add)
web_1  |   File "/opt/pdfsvc/page_request/admin.py", line 13, in save_model
web_1  |     obj.save()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
web_1  |     self.save_base(using=using, force_insert=force_insert,
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
web_1  |     updated = self._save_table(
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
web_1  |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
web_1  |     return manager._insert(
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
web_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
web_1  |     return query.get_compiler(using=using).execute_sql(returning_fields)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
web_1  |     cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
web_1  |     return super().execute(sql, params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
web_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
web_1  |     return executor(sql, params, many, context)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1  |     return self.cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
web_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1  |     return self.cursor.execute(sql, params)
web_1  | django.db.utils.ProgrammingError: relation "page_request_pagerequest" does not exist
web_1  | LINE 1: INSERT INTO "page_request_pagerequest" ("owner_id", "url", "...
web_1  |                     ^
web_1  | 
web_1  | [15/Jan/2022 16:47:25] "POST /admin/page_request/pagerequest/add/ HTTP/1.1" 500 176245

**Comment by betancourtf** [comment]
You need to run migrations. After starting the containers run in a different shell:
```
docker exec -it pdfsvc_web_1 bash
python manage.py makemigrations
python manage.py migrate
```
After that it should load correctly.
Make sure you take a look at the readme file.
